pool:
  vmImage: 'Ubuntu-16.04'

variables:
  sources_dir: /opt/rt-n56u

steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y git sudo module-init-tools autopoint autoconf automake bison build-essential flex gawk gettext gperf libtool pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev texinfo python-docutils mc
    displayName: 'Prepare build environment'

  - script: |
      sudo cp -rfv newifi-mini /opt
      sudo cp -fv patch.sh /opt
    displayName: 'Prepare newifi mini patch files'

  - script: |
      sudo git clone https://bitbucket.org/padavan/rt-n56u.git $(sources_dir)
    displayName: 'Get padavan sources'

  - script: |
      cd $(sources_dir)/toolchain-mipsel
      sudo ./clean_sources
      sudo ./build_toolchain
    displayName: 'Build toolchain'
  
  - script: |
      cd /opt
      sudo chmod +x patch.sh
      sudo ./patch.sh
    displayName: 'Patch sources'
  
  - script: |
      cd $(sources_dir)/trunk
      sudo ./clear_tree
      sudo ./build_firmware
    displayName: 'Build firmware'

  - script: |
      cd $(Build.ArtifactStagingDirectory)
      cp -v $(sources_dir)/trunk/images/*.trx .
      sha256sum *.trx | tee sha256.txt
    displayName: 'Prepare firmware and calculate sha256'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)
      artifactName: 'newifi-mini'
